name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
        with:
          extra-conf: sandbox = relaxed
      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Build
        run: nix-build
